# Generated by Django 4.2.6 on 2024-11-15 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0002_contest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='url',
        ),
    ]
